name: Update gist
on:
  repository_dispatch:
    types: [build-event]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 93ce49f92fa5179535c8e023f7ba9ffe
          TIMEZONE: Europe/Berlin
